### ISSUE TITLE
How to Consolidate Vulnerabilities?

### ISSUE THREAD

**Issue by brettforbes** [ossf/osv-schema#151]
So there are conceptual problems with this repo, and the data represented by it:
1. How does this data vary from that reported in Mitre CVE? https://cve.mitre.org/
2. How does the schema vary from that reported in Mitre?
3. Why is the schema different to the Mitre one? Is there a rationale, like stuff that is missing, or is it that you just want to be different? Why is there no rationale document outlining why the other standards are insufficient? The reasoning for this is not clear at all
4. Why is the schema not in Stix 2.1, with an extension if necessary? Why does OpenSSF not utilise other standards like OASIS Stix, and want to pursue its own (it doesn't make sense)? Is there a technical reason, is it history, based on dislike? Why, can you explain please?
5. Why is there no converter from your standard, to other standards? I mean we can build it ourselves, but why is it not there now? It certainly appears as you are the smaller standard https://www.cve.org/ProgramOrganization/CNAs
6. How to handle the numbering if there are different vulnerability databases using different numbering schemes? How can we merge the numbering?

If we want to build a mega vulnerability database, how can we do it? Do we add together your standard, and the Mitre standard?? How to do this? why is it so hard, and why is there no acknowledgment and discussion on how to integrate??

The main issue is working out how to join your bubble to the other bubbles. How should this be done and why is it not clearly outlined already? What about the CVE numbering?

Very confused

**Comment by oliverchang** [comment]
Hi, please see these blog posts which go in depth to answer many of your questions. 

https://security.googleblog.com/2021/06/announcing-unified-vulnerability-schema.html
https://security.googleblog.com/2023/03/osv-and-vulnerability-life-cycle.html

In short, OSV complements CVEs by enabling a much more open source-focused encoding of CVEs. Even prior to CVEs, we've already seen many different vulnerability databases that augment CVEs because it has been historically difficult to match CVEs to open source dependencies. All of these different IDs can still be linked together via [`aliases`](https://ossf.github.io/osv-schema/#aliases-field) (e.g. the original CVE ID).

Regarding converters, we have so far been prioritising other efforts around making OSV useful and easy to adopt. We also have been directly involved with the CVE 5.0 standard (which is currently being rolled out) to enable easier interop in the future.  I expect converters to come in due time.

**Comment by brettforbes** [comment]
hi @oliverchang 

Thanks for the feedback. We are just about to release an open-source system that imports Stix 2.1 and Mitre ATT&CK objects using the OASIS Stix Python Library. We plan on extending this to suit the OASIS CACAO standard as well as the OCA Kestrel threat hunting language. Also we are keen on supporting OASIS CSAF, SBOM's and a VEX over the next twelve months.

We would like to build a Stix extension for your schema, and an import method into the OASIS Stix2 Python Library (i.e. the ability to create, add, get and delete OSV objects) for your schema. Can we discuss how we might be able to go about doing that?

We would like to work with you guys to understand how best to integrate the two worlds, as there is clearly strong value in doing so. We would like to contribute code to your system to enable smooth integration between the two worlds.

Is this of interest and can we work together on these ideas?

**Comment by priamai** [comment]
hi @oliverchang ,
let me elaborate more, I am working together with @brettforbes to:

- expand the Vulnerability object in STIX2.1 to contain more properties such as the CVSS score and the EPSS score (I was one of the contributor to that project)
- add also a specific object for OSV, which as you mention will then be linked via an SRO to the new Vulneraiblity object
- then link together the vulnerabilities mentioned in a SBOM/VEX package

I had a look at the API which are good but we want to import all in bulk, do you have something like this? 
https://www.cve.org/Downloads

The current API has only a GET method via ID.

Thanks for your attention.

**Comment by oliverchang** [comment]
Hi, sorry for the slow replies here. We'd love to see support for the OSV schema in other standards. 

We provide bulk downloads via this: https://google.github.io/osv.dev/data/#data-dumps

Would that work for you? What else would be required from us to help?
