### ISSUE TITLE
Rename `WEB` to aid in clarity?

### ISSUE THREAD

**Issue by joshbuker** [ossf/osv-schema#65]
Currently the catch-all for references of an unknown type is "WEB". At first glance however, it's not necessarily clear that these are references of essentially an undefined or unknown type.

Some various alternatives:
- `UNKNOWN`
- `OTHER`
- `UNSPECIFIED`

@oliverchang this would be a pretty major change, but I think have some positive long term implications as far as keeping the data intuitive and reducing institutional knowledge required.

**Comment by oliverchang** [comment]
I believe our rationale for going with "WEB" is that it implies a generic web link, rather than some completely unspecified URL (which may not even point to a web page, e.g. "mailto:", "ftp://").

And similar to #66, renaming fields comes with a cost -- and it's not clear to me there's a strong benefit here in renaming this.

**Comment by joshbuker** [comment]
> I believe our rationale for going with "WEB" is that it implies a generic web link, rather than some completely unspecified URL (which may not even point to a web page, e.g. "mailto:", "ftp://").

Gotcha, thanks for the clarification!

> And similar to https://github.com/ossf/osv-schema/issues/66, renaming fields comes with a cost -- and it's not clear to me there's a strong benefit here in renaming this.

Agreed, and in retrospect there's better ways to solve this problem (e.g. tagging as opposed to categories). Closing.
